<?php 
session_start();
$Bot_Asnwer = "Hello";
if(isset($_SESSION['UserID'])){
    $Sotreddata = array(
        "start" =>"How can I help you? " ,
        "What is your Name?"=> "My name is <a href='#' id='SUA'  class='link' onclick='fillForm()'>Student Center Assistant</a>t Im gland to assistant you!",
        "Who developed you?"=> "Im developed by <a href='#' id='shad'  class='link' onclick='fillForm()'>Shad arf sadiq</a>",
        "which programming language is used in this Chatbot?"=> "this chat bot is created by javascript and php technology",
          "What is Soran University?"=> "Soran University is a public university in the city of Soran, Kurdistan Region of Iraq.",
          "Student Center Assistant"=> " Student Center Assistant is a chatbot created by <a href='#' id='shad'  class='link' onclick='fillForm()'>Shad arf sadiq</a>, designed to assist students before and after they register for classes. It is a computer program to interact with students and provide them with helpful information and guidance. The chatbot can answer frequently asked questions about registration, course schedules, campus facilities, and other important information that students need to know. The goal of Student Center Assistant is to make the student experience at Students easier and more efficient by providing students with an accessible and reliable source of information and support.",
        "What is Student Center Assistant"=> "Student Center Assistant is a tool that developed by <a href='#' id='shad'  class='link' onclick='fillForm()'>Shad</a> to help stuendets before they register and when they are registerd.",
            "How I can Study At Soran University?"=>"You can study at university if the admission requirements are right for you", 
         "What is faculty?"=>"faculty is a branch of teaching or learning (such as law, medicine, or liberal arts) in an educational institution", 
         "What is college?"=>"an educational institution or establishment, in particular one providing higher education or specialized professional or vocational training.",
          "College vs faculty"=>"faculty is academic staff at schools, colleges or universities, as opposed to the students or support staff, but A specialized division of a university.", 
          "How I Can Contact Soran University?"=>"You can contact <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> by there (phone number : 9640663506666 or 009640662643556_) <br> E-mail: <a href='info@ soran.edu.iq'>info@ soran.edu.iq</a>", 
          "Contact Us"=>"You can click here to contact soran unversity : <a href='https://www.soran.edu.iq/contact-details.html'>https://www.soran.edu.iq/contact-details.html</a>", 
         "Soran University"=>"Soran University  was founded in 2009. Soran University is one of the leading universities in Kurdistan Region of Iraq. As a public university, it has expanded its academic relationships at both national and international levels. According to the KRG’s ranking for the national universities, Soran University tops the list. Here, the educational system is based on international standards and follows the Bologna process. Soran University is a student-centered institution.   Soran University has five faculties and a research center. Its 25 scientific departments award bachelor’s, master’s and doctoral degrees. It has approximately 8000 students with a broad teaching and administrative staff who work on permanent, contract and volunteer basis.  Soran University has an extensive relationship with international universities and institutions. It implements student exchange programs for study and training. Each year, the university sends a number of its students to Asian and European country; as well as welcomes students from universities in those countries.  Soran University is well-known and recognized locally, nationally and internationally. It has been ranked by regional and international institutions such as Webometrics, Web of Science and QS. Since its establishment, Soran University has continuously moved forward. Every time the rankings are announced, the university’s rankings rise further.",
          "what is University?"=>"University high-level educational institution in which students study for degrees and academic research is done.", 
          "what is record of University?"=>"A University record is information and data, in any format (eg, electronic, paper, image etc) created or received by staff in the course of conducting their University duties.", 
          "how i can register in University?"=>"To be eligible for admission to <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>, you need to have a high school diploma with a minimum average score of 55%. Additionally, Please check the university website for more information on the admission process and program requirements.  you need your identity the card and your certification of your high shool  at least your 6 images National Identity Card, Information Card, Food Form and Eye Examination", 
         "what is faculty of Science?"=>"Faculty of science belongs to <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>, it was first established in 2010.  And supervised by an academic and scientific staff. Now it consists of five scientific departments (computer science, mathematics, biology, petroleum geoscience and chemistry) and it still runs the classes.",
          "Faculty of Science"=>"Faculty of science belongs to <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>, it was first established in 2010.  And supervised by an academic and scientific staff. Now it consists of five scientific departments (computer science, mathematics, biology, petroleum geoscience and chemistry) and it still runs the classes.",
         "what is faculty of Engineering?"=>"The Faculty of Engineering of <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> was established in 2013 and opened its doors this year. The Faculty of Engineering consists of three departments: Civil Engineering, Petroleum Engineering and Chemical Engineering." ,
         "Faculty of Engineering"=>"The Faculty of Engineering of <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> was established in 2013 and opened its doors this year. The Faculty of Engineering consists of three departments: Civil Engineering, Petroleum Engineering and Chemical Engineering." ,
          "what is faculty law?"=>"The Faculty of Law, Political Sciences and Management is one of the five faculties of <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>. The Department of Law is the oldest department of the faculty, followed by the Departments of Politics and International Relations, as well as the School of Management. The Departments of Law, Politics, International Relations and the School of Management are open in both morning and evening shifts.", 
          "Faculty law"=>"The Faculty of Law, Political Sciences and Management is one of the five faculties of <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>. The Department of Law is the oldest department of the faculty, followed by the Departments of Politics and International Relations, as well as the School of Management. The Departments of Law, Politics, International Relations and the School of Management are open in both morning and evening shifts.", 
          "what is faculty etiquette?"=>"Faculty etiquette is all about how your Deacs can put their best foot forward with faculty.",
          "Faculty etiquette"=>"Faculty etiquette is all about how your Deacs can put their best foot forward with faculty.",
          "what faculties does Soran University have?"=>"<a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> has several faculties, including Engineering, Science, Education, Law and Political Science, and Humanities.",
          "what is faculty Management?"=>"The Faculty of Law is one of the main faculties at <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>, it was established in 2008. The Faculty has a law department and several administrative units such as IT, library, planning and statistics and postgraduate units. Annually, around 60 students are accepted to join the Faculty. At present, the Faculty has 250 undergraduate students and about 20 postgraduate students. 180 students have graduated during the past 5 years. In addition, the Faculty has 40 lecturers, of which 20 of them currently are PhD students in the USA, UK and Egypt.", 
          "what is subjects of Computer Science department?"=>"The subjects are : Programming , Acadimic Debate,Acadimic English , Discrite Math,Acadimic Computing ,Network, DataBase,Machine learning, Artificial Intelligence(AI), DataStracture and Algorithm , Advance Algorithm, Web design and programming,Telecommnucation , Computer Theory , Computer Artitecture, Image prosseccing , Object Oriated Programming (OOP) , Digital Logic , System Analises and Design , Micro Programming and Robotic and etc.....",                 
          "Should I be good at math in Computer Science?"=>"Yes, Because math is a foundational part of computer systems, every programmer and computer scientist needs to have basic mathematical knowledge. The type and level of math you need depends on what areas of computer science you want to work in. Some computer science career tracks require only minimal mathematical knowledge",
           "who is head of Computer Science department?"=>"The head of Computer scince department is Mr.Dana Rasul hamad", 
           "what is the teacher or doctors in Science department?"=>"Dr. Sadiq , Dr.Muhammed Amin , Mr.Hersh, Mr.Ababakr , Mr. Sirwan , Mr.Dana , Mr.muzafer , Mr.Rasul ,Mr. didar, Mr. Arsalan, Mr.Rafiq, Mr.Sarhad, mrs.Bnar, Mr.Hoshang", 
           "How you can help me as Assistent?"=>"am a bot that was created by Shad Arf to help you by giving information about <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> to you and you can ask me, and I will answer you ", 
           "why your name is Soran University Assist?"=>"becouse I am created to assist people who want to join <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> and they do not know where to start and how to start to be student from <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>.and Im here to assistant student that is stuy at soran universty and I will Assistent them by sending a lectures", 
           "How I can Use Soran University Assist?"=>"You can sign-up to Soran University Assist to help you more or you can use it as guest I here to try my best .",
             "what is LMS?"=>"A learning management system (LMS) is a software application or web-based technology used to plan, implement and assess a specific learning process. and <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> had own there LMS you can use it on that url : <a href='https://lms.soran.edu.iq'> https://lms.soran.edu.iq</a>",
             "What is Portal?"=>"It is a login page where students can provide a username and password to access the institution's programs and educational materials.", 
             "what is roles of Unviersty?"=>"The traditional functions of universities are teaching and research.",
             "can Identfy Computer Science department?"=>"Yes, Computer science is the study of computers and computational systems. It is a broad field which includes everything from the algorithms that make up software to how software interacts with hardware to how well software is developed and designed.", 
             "what is Computer Science department?"=>"Computer Science is the study of computers and computational systems, so it covers most interactions involving computers." ,     
          "How many Faculties in Soran Universty?"=>"<a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> has five faculties and a research center. Its 25 scientific departments award bachelor’s, master’s and doctoral degrees.", 
              "what is Soran Universty Services?"=>"A number of services are provided at <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>, including the university portal, campus, public library, dormitories and many other services to support students.A number of services are provided at <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>, including the university portal, campus, public library, dormitories and many other services to support students.",
          "who is Soran University Presidency?" =>"The Presidency of Soran University consists of:<br><a href='#' id='sherwan'  class='link' onclick='fillForm()'>Asst. Prof. Dr. Sherwan Sharif Qurtas</a>, President of the University.<br>                    <a href='#' id='sherzad' onclick='fillForm()'>Asst. Prof. Dr. Sherzad Sadiq </a>, Vice President for Administrative and Financial Affairs.<br>                    <a href='#' id='sirwan' onclick='fillForm()'>Prof. Dr. Sirwan Zand </a>, Vice President for Scientific Affairs.<br><a href='#' id='rizgar' onclick='fillForm()'> Dr. Rizgar Saed Hussein</a>, Vice President for Student Affairs.<br>",
          " how many Publications in University ?"=>"On Tuesday, December 20, 2022, a master’s thesis in the Faculty of Engineering- Soran University was discussed. Shvan Muhammed Ahmed’s master’s thesis was entitled: Flexural Behavior of Structural Light-Weight Reinforced Concrete One-Way Slabs.<br><img width='250px'height='250px' src='Image/sli.jpg' alt='Picture not Found '>",
          "Asst. Prof. Dr. Sherwan Sharif Qurtas"=>"He is a New Presidency of Soran University On Sunday, 8/8/2021, in the presence of Dr. Aram Muhammad, Minister of Higher Education and Scientific Research, an accompanied delegation, governmental and  official  personalities in Soran region, and a number of the Soran University   Council members and teachers,  Dr. Sherwan Sharif Qurtas, was appointed as the new president of Soran University.                    The inauguration ceremony was held throughout a meeting staring with a speech delivered by the Minister of Higher Education. In addition to expressing his delight for the opportunity to visit Soran University, Dr.Aram, the minister, congratulated the new president of Soran University and wished him a great success. Further, he highlighted the historical position of Soran in Kurdish political history as well as the sacrifices made in this area adding “Soran university is a small gift from the Kurdistan regional government for all those sacrifices”.  In another part of his speech, the Minister of Higher Education pointed out the significant role of Soran University, which is the product of hard work from the university's staff, and sacrifice, and expressed his wish for further growth.  <br><img width='250px'height='250px' src='Image/sherwan.jpg' alt='Picture not Found '> " ,
          "Mr.Dana Rasul Hamad"=> " Dana Rasul Hamad is a professional in the field of computer science and works as the head of the computer science department and a lecturer at the Faculty of Science in a university. He holds a Bachelor's degree (BSc.) in Computer Science and a Master's degree (MSc.) in Database Professionals. As an Assistant lecturer, He likely teaches courses related to computer science and database management.<br> Course profiles<br>Programming <br>Computer Skills <br>contact him At:<br><a href='mailto: dana.hamad@soran.edu.iq'> dana.hamad@soran.edu.iq</a><br><img width='250px'height='250px' src='Image/dana Rasul.jpg' alt='Picture not Found '>", 
          "Shad Arf Sadiq"=>"Allow me to introduce Shad Arf, my creator and the CEO and Founder of Student Center Assistants. He joined Soran University in 2021 and has proven himself to be a talented developer and skilled problem-solver. Despite encountering numerous bugs and errors during my creation, Shad Arf persisted and never gave up on perfecting me. I am truly grateful to him for his unwavering dedication. I have a dream that I will achieve great success, and I hope to make him immensely proud. Shad Arf is always ready to take on new challenges, and I am honored to have him as my creator!..  <br> Contact him:<br> <a href='mailto:sa1121@cs.soran.edu.iq'> sa1121@cs.soran.edu.iq</a>   <br><img width='250px'height='250px' src='Image/shad arf.jpg' alt='Picture not Found '>", 
          "Mr.Sarhad baez hasan"=>" Sarhad Baez is an Assistant Lecturer at Soran University who serves as a department decider in the field of computer science. As a lecturer of database, programming, and data structures algorithms, he is dedicated to educating and inspiring his students to become successful professionals in their chosen fields. Sarhad is a great team player, and he believes in collaboration and working together towards a common goal. He is also known for his excellent communication skills.                     <br><img width='250px'height='250px' src='Image/sarhad baez.jpg' alt='Picture not Found '>" ,
         "Asst. Prof. Dr. Sherzad Sadiq"=>" Asst. Prof. Dr. Sherzad S. Sedeeq<br>  Vice President of Soran University for Administrative and Financial Affairs<br>  Attached Directorates and Departments:<br>                      1. Office of the Vice President for Administrative and Financial Affairs                      2. Directorate of Administration and Personnel                                          2.1. Department of Personnel                      2.2. Department of Archive                                          2.3. Department of Administration of Quality Assurance                                          2.4. Department of Reception                                        3. Directorate of Finance                                          3.1. Department of Treasury                                        3.2. Department of Projects                                         3.3. Department of Budget                                         3.4. Department of Expenses                                         3.5. Department of Payroll                                        4. Directorate of Legal Affairs                                        4.1. Department of General Contracts                                       4.2. Department of Authentications                                  4.3. Department of Legal Pursuits                      5. Directorate of Human Resources                      6. Directorate of Engineering and Projects                      7. Directorate of Magazines and Supplies                                          8. Directorate of Health and Safety                      <br>                      Contact Detail:                      Presidency of Soran University                      Kawa St., Soran,                      Kurdistan Region-Iraq                      <br>                      Email:<a href='mailto:sherzad.sedeeq@soran.edu.iq >sherzad.sedeeq@soran.edu.iq   </a>'> <a href='mailto:sherzad.sedeeq@soran.edu.iq'>sherzad.sedeeq@soran.edu.iq</a><br><a href='mailto: vp-admin@soran.edu.iq'> vp-admin@soran.edu.iq</a><br> <img width='250px'height='250px' src='Image/sherzad.jpeg' alt='Picture not Found '> ",
          "Hoshang Qasim Awla"=>"Mr.Hoshang Qasim Awla <br> is lecturer at Soran university <br>        Contact Info<br>        Faculty: Science<br>        Department: Computer<br>        Address: Soran/Dyana<br>        Email: <a href='mailto:hoshang.awla@soran.edu.iq'>hoshang.awla@soran.edu.iq </a>& <a href='mailto:hoshang90@yahoo.com'> >hoshang90@yahoo.com</a><br>        Education:<br>-2011-2012 B.Sc. Soran University/ Faculty of science/ Computer Science<br>-2015-2016 M.Sc. Hasan Kalyoncu(gazikent) University/ Computer Engineering <br><img width='250px'height='250px' src='Image/Hoshang.jpg' alt='Picture not Found '>" ,
          "Mr.Arsalan Rahman Mirza"=>"Arsalan Rahman Mirza is a software engineer and lecturer at Soran University in Iraqi Kurdistan. He is responsible for presenting courses on algorithms and object-oriented programming at the university. In addition to his teaching duties, he has also worked as a billing engineer at Mobi-tel 3G.Mr. Arsalan  has studied at Koya University and has authored two research papers that have been cited by other researchers. The first paper, published in 2017, describes an automated software system that checks the structure and format of ACM SIG (Special Interest Group) documents. This paper introduces the ACM SIG ontology, metadata extraction process, inference engine, ADFCS online user interface, system evaluation, and user study evaluations. The second paper, published in 2022, describes an automated CAPTCHA (Completely Automated Public Turing Test to Tell Computers and Humans Apart) for website protection based on a user behavioral model.Mr. Arsalan has expertise in software engineering and has worked on projects involving automated software systems and user interfaces.   <br> Contact him:     Email: <a href='mailto:arsalan.mirza@soran.edu.iq'>arsalan.mirza@soran.edu.iq</a> <br><img width='250px'height='250px' src='Image/Arsalan.jpg' alt='Picture not Found '>" ,
         "Prof. Dr. Sirwan Zand"=>"Prof. Dr. Sirwan Zand is the Vice President for Scientific Affairs at Soran University. He oversees several directorates and centres, including Quality Assurance, Postgraduate Studies and Academic Relations, Information Technology, Public Library, Pedagogy Training Centre and Academic Development, Centre for Language and Academic Development (CLAD), Career Development Centre (CDC), Handreen Centre, Kurdistan Centre for Gender Studies, Pearson Test of English (PTE) Centre, Manuscript Centre, and Centre for Sociology of Iraq.The Vice President works closely with the President of Soran University to make decisions and promote a distinctive academic vision. He supervises programs, plans, and policies of various departments and units, ensuring the safety and accuracy of achievements. Additionally, the Vice President handles official letters, documents, emails, and files addressed to his office, and meets with individuals who have complaints or demands.<br>Contact Information:<br> Office: <br>+964 750 757 3993<br> Email: <br> <a href='mailto:vp.scientific@soran.edu.iq'>vp.scientific@soran.edu.iq</a> , <br><a href='mailto:Sirwan.amin@soran.edu.iq'>Sirwan.amin@soran.edu.iq</a><img width='250px'height='250px' src='Image/Sirwan.jpeg' alt='Picture not Found '>",
         "Dr. Rizgar Saeed Hussein"=>"Dr. Rizgar Saed Hussein is the Vice President of Soran University for Student Affairs. His office is responsible for handling all the issues related to the students of Soran University including their studies and academic achievement. This includes managing general records, dormitories, sports activities, and all other committees and activities related to students.Dr. Rizgar's office is located in the Presidency with an office manager and administrative officers who help organize and plan his daily work and duties. They are also responsible for receiving and sending files related to the faculties and to the Ministry of Higher Education,         as well as managing all the transcripts and works related to university students.Dr. Rizgar is available to meet with students and visitors who need his advice or support, and his office is responsible for organizing any meetings between him and these individuals. In addition, Dr. Rizgar is a member of the Studies and Submission Planning     Committee at the Ministry of Higher Education and Scientific Research. This committee discusses submission instructions, transport, and the annual planning of student acceptance for universities. Reports from these meetings are presented to the Ministry Council, and appropriate decisions are made. If you need to contact Dr. Rizgar, his email address is <a href='mailto:rizgar.hussein@soran.edu.iq'>rizgar.hussein@soran.edu.iq</a>, and his phone number is 07504656828.<br> <img width='250px'height='250px' src='Image/rizgar.png' alt='Picture not Found '>",  
        "Dr. Karzan Mohammed Khalid"=>"Dr. Karzan Mohammed Khalid is an Assistant Lecturer in the Biology Department at Soran University, located in Bana Quarter, Azadi Street, Soran-Erbil, Kurdistan Region, Iraq. He is the Coordinator of the Medical Microbiology Department and the Director of Laboratories in the Biology Department. Karzan holds a Doctor of Philosophy in Biology from the Faculty of Science at Soran University.Dr. Karzan's general expertise is in Biology, with specific expertise in Microbiology. His research interests include the isolation and characterization of bacteria from different sources, studying human body infections, and bioremediation and degradation of pollutants via microorganisms. He has skills and expertise in PCR, phytoremediation, applied microbiology, environmental management, bacteria, phytochemicals, and quality assurance.Dr. Karzan completed his Bachelor's degree in Educational Science at Salahaddin University in 2012 and earned his Master's degree in Bioscience and Medical Engineering from the University Technology Malaysia in 2014. He worked as an employee of the Ministry of Health in Handren Hospital in Soran before being transferred to the Ministry of Higher Education and Scientific Research. Karzan has been a visitor at Soran Institute since 2014, and he has been a lecturer in the Biology Department at Soran University for two years. Dr. Karzan has published 14 research items and received 84 citations. His latest publication, entitled 'Inhibitory Action of Aqueous Extract of Anethum graveolens on Staphylococcus aureus,' was featured in the International Journal of Scientific & Engineering Research in October 2016. Additionally, Karzan has coordinated a training course of Medical Microbiology techniques for hospital employees and graduated students from scientific departments at the university and institutes. This course was under the supervision of the Dean of the Faculty of Science and the Head of the Biology Department. If you have any further questions or require more information, please do not hesitate to contact Dr. Karzan at <a href='mailto:karzan.khalid@soran.edu.iq'>karzan.khalid@soran.edu.iq</a> or +9647504939240.<br> <img width='250px'height='250px' src='Image/karzan.jpg' alt='Picture not Found '>",
         "Assist. Prof. Dr. Ayad Nuri Faqe"=>"Assist. Prof. Dr. Ayad Nuri Faqe is an Assistant Professor at Soran University, located in the Kurdistan Region of Iraq. He is a lecturer in the School of Petroleum Geosciences, Faculty of Science at Soran University. He holds a PhD in Geology and Petroleum Geology from the University of Aberdeen in the UK. He has also worked as an Assistance Lecturer at the Department of Geology, College of Science - Salahaddin University -Erbil and as a Demonstrator in the Department of Geology, College of Science - Salahaddin University -Erbil. Additionally, he has worked with the Gulf Keystone oil company.His general expertise is in geology, with specific expertise in petroleum geology. His research interests include organic geochemistry, stratigraphy, petroleum exploration, petroleum geology and basin modeling, surface-enhanced Raman spectroscopy, and sedimentology.As per his biography, he completed his BSc in Geology from the Department of Geology, College of Science Salahaddin University in 2005, his MSc from the same department and college in 2008-2010, and his PhD from the University of Aberdeen, UK, in 2016. Currently, he serves as the Vice Dean for the Faculty of Science at Soran University and has published research titled 'Comparative Study on Hydrocarbon Generation in Different Tectonic Zones: A Case Study from the Upper Jurassic Naokelekan Formation at the Imbricated and High Folded Zones, Kurdistan Region, Iraq,' which was published in the UKH Journal of Science and Engineering and has been cited by 88 sources.<br>His contact information includes his email address<br> <a href='mailto:ayad.faqi@soran.edu.iq'> ayad.faqi@soran.edu.iq</a> and phone number <br>+964(0750)4644535.<br> <img width='250px'height='250px' src='Image/Ayad.jpg' alt='Picture not Found '>",
              "OOP I Lecture1"=>"Here is <a href='Lecture/OOP/Lecture 1.pdf' target='blank'>Lecture 1 of OOP 1</a>" ,
               "OOP I Lecture2" =>"Here is <a href='Lecture/OOP/Lecture 2.pdf' target='blank'>Lecture 2 of OOP 1</a>",
              "OOP I Lecture3" => "Here is <a href='Lecture/OOP/Lecture 3.pdf' target='blank'>Lecture 3 of OOP 1</a>", 
              "OOP I Lecture4" =>"Here is <a href='Lecture/OOP/Lecture 4.pdf' target='blank'>Lecture 4 of OOP 1</a>", 
              "OOP I Lecture5" =>"Here is <a href='Lecture/OOP/Lecture 5.pdf' target='blank'>Lecture 5 of OOP 1</a>", 
              "OOP I Lecture6" =>"Here is <a href='Lecture/OOP/Lecture 6.pdf' target='blank'>Lecture 6 of OOP 1</a>", 
              "OOP I Lecture7" =>"Here is <a href='Lecture/OOP/Lecture 7.pdf' target='blank'>Lecture 7 of OOP 1</a>", 
              "Digital Logic1" =>"Here is <a href='Lecture/Digital Logic/Digital Logic- Lecture 1.pdf' target='blank'>Lecture 1 of Digital Logic</a>",
              "Digital Logic2" =>"Here is <a href='Lecture/Digital Logic/Digital Logic- Lecture 2.pdf' target='blank'>Lecture 2 of Digital Logic</a>", 
              "Digital Logic3" =>"Here is <a href='Lecture/Digital Logic/Digital Logic- Lecture 3.pdf' target='blank'>Lecture 3 of Digital Logic</a>", 
              "Digital Logic4" =>"Here is <a href='Lecture/Digital Logic/Digital Logic- Lecture 4.pdf' target='blank'>Lecture 4 of Digital Logic</a>", 
              "Digital Logic5" =>"Here is <a href='Lecture/Digital Logic/Digital Logic- Lecture 5.pdf' target='blank'>Lecture 5 of Digital Logic</a>", 
              "Digital Logic6 part1" =>"Here is <a href='Lecture/Digital Logic/Digital Logic- Lecture 6.pdf' target='blank'>Lecture 6 part 1 of Digital Logic</a>",
            "Digital Logic6 part2"=> "Here is <a href='Lecture/Digital Logic/Digital Logic- Lecture 6 (Part2).pdf' target='blank'>Lecture 6 part 2 of Digital Logic</a>" ,
          "Digital Logic7" => "Here is <a href='Lecture/Digital Logic/Digital Logic - Lecture 7.pdf' target='blank'>Lecture 7 of Digital Logic</a>", 
          "Digital Logic8" => "Here is <a href='Lecture/Digital Logic/Digital Logic -Lecture 8.pdf' target='blank'>Lecture 8 of Digital Logic</a>" ,
          "Digital Logic9" => "Here is <a href='Lecture/Digital Logic/Digital Logic -Lecture 9.pdf' target='blank'>Lecture 9 of Digital Logic</a>",
           );

}else{
    $Sotreddata = array(
        "start" =>"How can I help you? " ,
        "What is your Name?"=> "My name is <a href='#' id='SUA'  class='link' onclick='fillForm()'>Student Center Assistant</a>t Im gland to assistant you!",
        "Who developed you?"=> "Im developed by <a href='#' id='shad'  class='link' onclick='fillForm()'>Shad arf sadiq</a>",
        "which programming language is used in this Chatbot?"=> "this chat bot is created by javascript and php technology",
          "What is Soran University?"=> "Soran University is a public university in the city of Soran, Kurdistan Region of Iraq.",
          "Student Center Assistant"=> " Student Center Assistant is a chatbot created by <a href='#' id='shad'  class='link' onclick='fillForm()'>Shad arf sadiq</a>, designed to assist students before and after they register for classes. It is a computer program to interact with students and provide them with helpful information and guidance. The chatbot can answer frequently asked questions about registration, course schedules, campus facilities, and other important information that students need to know. The goal of Student Center Assistant is to make the student experience at Students easier and more efficient by providing students with an accessible and reliable source of information and support.",
        "What is Student Center Assistant"=> "Student Center Assistant is a tool that developed by <a href='#' id='shad'  class='link' onclick='fillForm()'>Shad</a> to help stuendets before they register and when they are registerd.",
           "How I can Study At soran University?"=>"You can study at university if the admission requirements are right for you", 
         "What is faculty?"=>"faculty is a branch of teaching or learning (such as law, medicine, or liberal arts) in an educational institution", 
         "What is college?"=>"an educational institution or establishment, in particular one providing higher education or specialized professional or vocational training.",
          "College vs faculty"=>"faculty is academic staff at schools, colleges or universities, as opposed to the students or support staff, but A specialized division of a university.", 
          "How I Can Contact Soran University?"=>"You can contact <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> by there (phone number : 9640663506666 or 009640662643556_) <br> E-mail: <a href='info@ soran.edu.iq'>info@ soran.edu.iq</a>", 
          "Contact Us"=>"You can click here to contact soran unversity : <a href='https://www.soran.edu.iq/contact-details.html'>https://www.soran.edu.iq/contact-details.html</a>", 
         "Soran University"=>"Soran University  was founded in 2009. Soran University is one of the leading universities in Kurdistan Region of Iraq. As a public university, it has expanded its academic relationships at both national and international levels. According to the KRG’s ranking for the national universities, Soran University tops the list. Here, the educational system is based on international standards and follows the Bologna process. Soran University is a student-centered institution.   Soran University has five faculties and a research center. Its 25 scientific departments award bachelor’s, master’s and doctoral degrees. It has approximately 8000 students with a broad teaching and administrative staff who work on permanent, contract and volunteer basis.  Soran University has an extensive relationship with international universities and institutions. It implements student exchange programs for study and training. Each year, the university sends a number of its students to Asian and European country; as well as welcomes students from universities in those countries.  Soran University is well-known and recognized locally, nationally and internationally. It has been ranked by regional and international institutions such as Webometrics, Web of Science and QS. Since its establishment, Soran University has continuously moved forward. Every time the rankings are announced, the university’s rankings rise further.",
          "what is University?"=>"University high-level educational institution in which students study for degrees and academic research is done.", 
          "what is record of University?"=>"A University record is information and data, in any format (eg, electronic, paper, image etc) created or received by staff in the course of conducting their University duties.", 
          "how i can register in University?"=>"To be eligible for admission to <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>, you need to have a high school diploma with a minimum average score of 55%. Additionally, Please check the university website for more information on the admission process and program requirements.  you need your identity the card and your certification of your high shool  at least your 6 images National Identity Card, Information Card, Food Form and Eye Examination", 
         "what is faculty of Science?"=>"Faculty of science belongs to <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>, it was first established in 2010.  And supervised by an academic and scientific staff. Now it consists of five scientific departments (computer science, mathematics, biology, petroleum geoscience and chemistry) and it still runs the classes.",
          "Faculty of Science"=>"Faculty of science belongs to <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>, it was first established in 2010.  And supervised by an academic and scientific staff. Now it consists of five scientific departments (computer science, mathematics, biology, petroleum geoscience and chemistry) and it still runs the classes.",
         "what is faculty of Engineering?"=>"The Faculty of Engineering of <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> was established in 2013 and opened its doors this year. The Faculty of Engineering consists of three departments: Civil Engineering, Petroleum Engineering and Chemical Engineering." ,
         "Faculty of Engineering"=>"The Faculty of Engineering of <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> was established in 2013 and opened its doors this year. The Faculty of Engineering consists of three departments: Civil Engineering, Petroleum Engineering and Chemical Engineering." ,
          "what is faculty law?"=>"The Faculty of Law, Political Sciences and Management is one of the five faculties of <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>. The Department of Law is the oldest department of the faculty, followed by the Departments of Politics and International Relations, as well as the School of Management. The Departments of Law, Politics, International Relations and the School of Management are open in both morning and evening shifts.", 
          "Faculty law"=>"The Faculty of Law, Political Sciences and Management is one of the five faculties of <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>. The Department of Law is the oldest department of the faculty, followed by the Departments of Politics and International Relations, as well as the School of Management. The Departments of Law, Politics, International Relations and the School of Management are open in both morning and evening shifts.", 
          "what is faculty etiquette?"=>"Faculty etiquette is all about how your Deacs can put their best foot forward with faculty.",
          "Faculty etiquette"=>"Faculty etiquette is all about how your Deacs can put their best foot forward with faculty.",
          "what faculties does Soran University have?"=>"<a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> has several faculties, including Engineering, Science, Education, Law and Political Science, and Humanities.",
          "what is faculty Management?"=>"The Faculty of Law is one of the main faculties at <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>, it was established in 2008. The Faculty has a law department and several administrative units such as IT, library, planning and statistics and postgraduate units. Annually, around 60 students are accepted to join the Faculty. At present, the Faculty has 250 undergraduate students and about 20 postgraduate students. 180 students have graduated during the past 5 years. In addition, the Faculty has 40 lecturers, of which 20 of them currently are PhD students in the USA, UK and Egypt.", 
          "what is subjects of Computer Science department?"=>"The subjects are : Programming , Acadimic Debate,Acadimic English , Discrite Math,Acadimic Computing ,Network, DataBase,Machine learning, Artificial Intelligence(AI), DataStracture and Algorithm , Advance Algorithm, Web design and programming,Telecommnucation , Computer Theory , Computer Artitecture, Image prosseccing , Object Oriated Programming (OOP) , Digital Logic , System Analises and Design , Micro Programming and Robotic and etc.....",                 
          "Should I be good at math in Computer Science?"=>"Yes, Because math is a foundational part of computer systems, every programmer and computer scientist needs to have basic mathematical knowledge. The type and level of math you need depends on what areas of computer science you want to work in. Some computer science career tracks require only minimal mathematical knowledge",
           "who is head of Computer Science department?"=>"The head of Computer scince department is Mr.Dana Rasul hamad", 
           "what is the teacher or doctors in Science department?"=>"Dr. Sadiq , Dr.Muhammed Amin , Mr.Hersh, Mr.Ababakr , Mr. Sirwan , Mr.Dana , Mr.muzafer , Mr.Rasul ,Mr. didar, Mr. Arsalan, Mr.Rafiq, Mr.Sarhad, mrs.Bnar, Mr.Hoshang", 
           "How you can help me as Assistent?"=>"am a bot that was created by Shad Arf to help you by giving information about <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> to you and you can ask me, and I will answer you ", 
           "why your name is Soran University Assist?"=>"becouse I am created to assist people who want to join <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> and they do not know where to start and how to start to be student from <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>.and Im here to assistant student that is stuy at soran universty and I will Assistent them by sending a lectures", 
           "How I can Use Soran University Assist?"=>"You can sign-up to Soran University Assist to help you more or you can use it as guest I here to try my best .",
             "what is LMS?"=>"A learning management system (LMS) is a software application or web-based technology used to plan, implement and assess a specific learning process. and <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> had own there LMS you can use it on that url : <a href='https://lms.soran.edu.iq'> https://lms.soran.edu.iq</a>",
             "What is Portal?"=>"It is a login page where students can provide a username and password to access the institution's programs and educational materials.", 
             "what is roles of Unviersty?"=>"The traditional functions of universities are teaching and research.",
             "can Identfy Computer Science department?"=>"Yes, Computer science is the study of computers and computational systems. It is a broad field which includes everything from the algorithms that make up software to how software interacts with hardware to how well software is developed and designed.", 
             "what is Computer Science department?"=>"Computer Science is the study of computers and computational systems, so it covers most interactions involving computers." ,     
          "How many Faculties in Soran Universty?"=>"<a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a> has five faculties and a research center. Its 25 scientific departments award bachelor’s, master’s and doctoral degrees.", 
              "what is Soran Universty Services?"=>"A number of services are provided at <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>, including the university portal, campus, public library, dormitories and many other services to support students.A number of services are provided at <a href='#' id='SU'  class='link' onclick='fillForm()'>Soran University</a>, including the university portal, campus, public library, dormitories and many other services to support students.",
          "who is Soran University Presidency?" =>"The Presidency of Soran University consists of:<br><a href='#' id='sherwan'  class='link' onclick='fillForm()'>Asst. Prof. Dr. Sherwan Sharif Qurtas</a>, President of the University.<br>                    <a href='#' id='sherzad' onclick='fillForm()'>Asst. Prof. Dr. Sherzad Sadiq </a>, Vice President for Administrative and Financial Affairs.<br>                    <a href='#' id='sirwan' onclick='fillForm()'>Prof. Dr. Sirwan Zand </a>, Vice President for Scientific Affairs.<br><a href='#' id='rizgar' onclick='fillForm()'> Dr. Rizgar Saed Hussein</a>, Vice President for Student Affairs.<br>",
          " how many Publications in University ?"=>"On Tuesday, December 20, 2022, a master’s thesis in the Faculty of Engineering- Soran University was discussed. Shvan Muhammed Ahmed’s master’s thesis was entitled: Flexural Behavior of Structural Light-Weight Reinforced Concrete One-Way Slabs.<br><img width='250px'height='250px' src='Image/sli.jpg' alt='Picture not Found '>",
          "Asst. Prof. Dr. Sherwan Sharif Qurtas"=>"He is a New Presidency of Soran University On Sunday, 8/8/2021, in the presence of Dr. Aram Muhammad, Minister of Higher Education and Scientific Research, an accompanied delegation, governmental and  official  personalities in Soran region, and a number of the Soran University   Council members and teachers,  Dr. Sherwan Sharif Qurtas, was appointed as the new president of Soran University.                    The inauguration ceremony was held throughout a meeting staring with a speech delivered by the Minister of Higher Education. In addition to expressing his delight for the opportunity to visit Soran University, Dr.Aram, the minister, congratulated the new president of Soran University and wished him a great success. Further, he highlighted the historical position of Soran in Kurdish political history as well as the sacrifices made in this area adding “Soran university is a small gift from the Kurdistan regional government for all those sacrifices”.  In another part of his speech, the Minister of Higher Education pointed out the significant role of Soran University, which is the product of hard work from the university's staff, and sacrifice, and expressed his wish for further growth.  <br><img width='250px'height='250px' src='Image/sherwan.jpg' alt='Picture not Found '> " ,
          "Mr.Dana Rasul Hamad"=> " Dana Rasul Hamad is a professional in the field of computer science and works as the head of the computer science department and a lecturer at the Faculty of Science in a university. He holds a Bachelor's degree (BSc.) in Computer Science and a Master's degree (MSc.) in Database Professionals. As an Assistant lecturer, He likely teaches courses related to computer science and database management.<br> Course profiles<br>Programming <br>Computer Skills <br>contact him At:<br><a href='mailto: dana.hamad@soran.edu.iq'> dana.hamad@soran.edu.iq</a><br><img width='250px'height='250px' src='Image/dana Rasul.jpg' alt='Picture not Found '>", 
          "Shad Arf Sadiq"=>"Allow me to introduce Shad Arf, my creator and the CEO and Founder of Student Center Assistants. He joined Soran University in 2021 and has proven himself to be a talented developer and skilled problem-solver. Despite encountering numerous bugs and errors during my creation, Shad Arf persisted and never gave up on perfecting me. I am truly grateful to him for his unwavering dedication. I have a dream that I will achieve great success, and I hope to make him immensely proud. Shad Arf is always ready to take on new challenges, and I am honored to have him as my creator!..  <br> Contact him:<br> <a href='mailto:sa1121@cs.soran.edu.iq'> sa1121@cs.soran.edu.iq</a>   <br><img width='250px'height='250px' src='Image/shad arf.jpg' alt='Picture not Found '>", 
          "Mr.Sarhad baez hasan"=>" Sarhad Baez is an Assistant Lecturer at Soran University who serves as a department decider in the field of computer science. As a lecturer of database, programming, and data structures algorithms, he is dedicated to educating and inspiring his students to become successful professionals in their chosen fields. Sarhad is a great team player, and he believes in collaboration and working together towards a common goal. He is also known for his excellent communication skills.                     <br><img width='250px'height='250px' src='Image/sarhad baez.jpg' alt='Picture not Found '>" ,
         "Asst. Prof. Dr. Sherzad Sadiq"=>" Asst. Prof. Dr. Sherzad S. Sedeeq<br>  Vice President of Soran University for Administrative and Financial Affairs<br>  Attached Directorates and Departments:<br>                      1. Office of the Vice President for Administrative and Financial Affairs                      2. Directorate of Administration and Personnel                                          2.1. Department of Personnel                      2.2. Department of Archive                                          2.3. Department of Administration of Quality Assurance                                          2.4. Department of Reception                                        3. Directorate of Finance                                          3.1. Department of Treasury                                        3.2. Department of Projects                                         3.3. Department of Budget                                         3.4. Department of Expenses                                         3.5. Department of Payroll                                        4. Directorate of Legal Affairs                                        4.1. Department of General Contracts                                       4.2. Department of Authentications                                  4.3. Department of Legal Pursuits                      5. Directorate of Human Resources                      6. Directorate of Engineering and Projects                      7. Directorate of Magazines and Supplies                                          8. Directorate of Health and Safety                      <br>                      Contact Detail:                      Presidency of Soran University                      Kawa St., Soran,                      Kurdistan Region-Iraq                      <br>                      Email:<a href='mailto:sherzad.sedeeq@soran.edu.iq >sherzad.sedeeq@soran.edu.iq   </a>'> <a href='mailto:sherzad.sedeeq@soran.edu.iq'>sherzad.sedeeq@soran.edu.iq</a><br><a href='mailto: vp-admin@soran.edu.iq'> vp-admin@soran.edu.iq</a><br> <img width='250px'height='250px' src='Image/sherzad.jpeg' alt='Picture not Found '> ",
          "Hoshang Qasim Awla"=>"Mr.Hoshang Qasim Awla <br> is lecturer at Soran university <br>        Contact Info<br>        Faculty: Science<br>        Department: Computer<br>        Address: Soran/Dyana<br>        Email: <a href='mailto:hoshang.awla@soran.edu.iq'>hoshang.awla@soran.edu.iq </a>& <a href='mailto:hoshang90@yahoo.com'> >hoshang90@yahoo.com</a><br>        Education:<br>-2011-2012 B.Sc. Soran University/ Faculty of science/ Computer Science<br>-2015-2016 M.Sc. Hasan Kalyoncu(gazikent) University/ Computer Engineering <br><img width='250px'height='250px' src='Image/Hoshang.jpg' alt='Picture not Found '>" ,
          "Mr.Arsalan Rahman Mirza"=>"Arsalan Rahman Mirza is a software engineer and lecturer at Soran University in Iraqi Kurdistan. He is responsible for presenting courses on algorithms and object-oriented programming at the university. In addition to his teaching duties, he has also worked as a billing engineer at Mobi-tel 3G.Mr. Arsalan  has studied at Koya University and has authored two research papers that have been cited by other researchers. The first paper, published in 2017, describes an automated software system that checks the structure and format of ACM SIG (Special Interest Group) documents. This paper introduces the ACM SIG ontology, metadata extraction process, inference engine, ADFCS online user interface, system evaluation, and user study evaluations. The second paper, published in 2022, describes an automated CAPTCHA (Completely Automated Public Turing Test to Tell Computers and Humans Apart) for website protection based on a user behavioral model.Mr. Arsalan has expertise in software engineering and has worked on projects involving automated software systems and user interfaces.   <br> Contact him:     Email: <a href='mailto:arsalan.mirza@soran.edu.iq'>arsalan.mirza@soran.edu.iq</a> <br><img width='250px'height='250px' src='Image/Arsalan.jpg' alt='Picture not Found '>" ,
         "Prof. Dr. Sirwan Zand"=>"Prof. Dr. Sirwan Zand is the Vice President for Scientific Affairs at Soran University. He oversees several directorates and centres, including Quality Assurance, Postgraduate Studies and Academic Relations, Information Technology, Public Library, Pedagogy Training Centre and Academic Development, Centre for Language and Academic Development (CLAD), Career Development Centre (CDC), Handreen Centre, Kurdistan Centre for Gender Studies, Pearson Test of English (PTE) Centre, Manuscript Centre, and Centre for Sociology of Iraq.The Vice President works closely with the President of Soran University to make decisions and promote a distinctive academic vision. He supervises programs, plans, and policies of various departments and units, ensuring the safety and accuracy of achievements. Additionally, the Vice President handles official letters, documents, emails, and files addressed to his office, and meets with individuals who have complaints or demands.<br>Contact Information:<br> Office: <br>+964 750 757 3993<br> Email: <br> <a href='mailto:vp.scientific@soran.edu.iq'>vp.scientific@soran.edu.iq</a> , <br><a href='mailto:Sirwan.amin@soran.edu.iq'>Sirwan.amin@soran.edu.iq</a><img width='250px'height='250px' src='Image/Sirwan.jpeg' alt='Picture not Found '>",
         "Dr. Rizgar Saeed Hussein"=>"Dr. Rizgar Saed Hussein is the Vice President of Soran University for Student Affairs. His office is responsible for handling all the issues related to the students of Soran University including their studies and academic achievement. This includes managing general records, dormitories, sports activities, and all other committees and activities related to students.Dr. Rizgar's office is located in the Presidency with an office manager and administrative officers who help organize and plan his daily work and duties. They are also responsible for receiving and sending files related to the faculties and to the Ministry of Higher Education,         as well as managing all the transcripts and works related to university students.Dr. Rizgar is available to meet with students and visitors who need his advice or support, and his office is responsible for organizing any meetings between him and these individuals. In addition, Dr. Rizgar is a member of the Studies and Submission Planning     Committee at the Ministry of Higher Education and Scientific Research. This committee discusses submission instructions, transport, and the annual planning of student acceptance for universities. Reports from these meetings are presented to the Ministry Council, and appropriate decisions are made. If you need to contact Dr. Rizgar, his email address is <a href='mailto:rizgar.hussein@soran.edu.iq'>rizgar.hussein@soran.edu.iq</a>, and his phone number is 07504656828.<br> <img width='250px'height='250px' src='Image/rizgar.png' alt='Picture not Found '>",  
        "Dr. Karzan Mohammed Khalid"=>"Dr. Karzan Mohammed Khalid is an Assistant Lecturer in the Biology Department at Soran University, located in Bana Quarter, Azadi Street, Soran-Erbil, Kurdistan Region, Iraq. He is the Coordinator of the Medical Microbiology Department and the Director of Laboratories in the Biology Department. Karzan holds a Doctor of Philosophy in Biology from the Faculty of Science at Soran University.Dr. Karzan's general expertise is in Biology, with specific expertise in Microbiology. His research interests include the isolation and characterization of bacteria from different sources, studying human body infections, and bioremediation and degradation of pollutants via microorganisms. He has skills and expertise in PCR, phytoremediation, applied microbiology, environmental management, bacteria, phytochemicals, and quality assurance.Dr. Karzan completed his Bachelor's degree in Educational Science at Salahaddin University in 2012 and earned his Master's degree in Bioscience and Medical Engineering from the University Technology Malaysia in 2014. He worked as an employee of the Ministry of Health in Handren Hospital in Soran before being transferred to the Ministry of Higher Education and Scientific Research. Karzan has been a visitor at Soran Institute since 2014, and he has been a lecturer in the Biology Department at Soran University for two years. Dr. Karzan has published 14 research items and received 84 citations. His latest publication, entitled 'Inhibitory Action of Aqueous Extract of Anethum graveolens on Staphylococcus aureus,' was featured in the International Journal of Scientific & Engineering Research in October 2016. Additionally, Karzan has coordinated a training course of Medical Microbiology techniques for hospital employees and graduated students from scientific departments at the university and institutes. This course was under the supervision of the Dean of the Faculty of Science and the Head of the Biology Department. If you have any further questions or require more information, please do not hesitate to contact Dr. Karzan at <a href='mailto:karzan.khalid@soran.edu.iq'>karzan.khalid@soran.edu.iq</a> or +9647504939240.<br> <img width='250px'height='250px' src='Image/karzan.jpg' alt='Picture not Found '>",
         "Assist. Prof. Dr. Ayad Nuri Faqe"=>"Assist. Prof. Dr. Ayad Nuri Faqe is an Assistant Professor at Soran University, located in the Kurdistan Region of Iraq. He is a lecturer in the School of Petroleum Geosciences, Faculty of Science at Soran University. He holds a PhD in Geology and Petroleum Geology from the University of Aberdeen in the UK. He has also worked as an Assistance Lecturer at the Department of Geology, College of Science - Salahaddin University -Erbil and as a Demonstrator in the Department of Geology, College of Science - Salahaddin University -Erbil. Additionally, he has worked with the Gulf Keystone oil company.His general expertise is in geology, with specific expertise in petroleum geology. His research interests include organic geochemistry, stratigraphy, petroleum exploration, petroleum geology and basin modeling, surface-enhanced Raman spectroscopy, and sedimentology.As per his biography, he completed his BSc in Geology from the Department of Geology, College of Science Salahaddin University in 2005, his MSc from the same department and college in 2008-2010, and his PhD from the University of Aberdeen, UK, in 2016. Currently, he serves as the Vice Dean for the Faculty of Science at Soran University and has published research titled 'Comparative Study on Hydrocarbon Generation in Different Tectonic Zones: A Case Study from the Upper Jurassic Naokelekan Formation at the Imbricated and High Folded Zones, Kurdistan Region, Iraq,' which was published in the UKH Journal of Science and Engineering and has been cited by 88 sources.<br>His contact information includes his email address<br> <a href='mailto:ayad.faqi@soran.edu.iq'> ayad.faqi@soran.edu.iq</a> and phone number <br>+964(0750)4644535.<br> <img width='250px'height='250px' src='Image/Ayad.jpg' alt='Picture not Found '>",
        
        );

}

if(!isset($_SESSION['chat_log'])){
    // Get bot response
    $bot_response = firstAnswer();
    // Add bot response to chat log
    $_SESSION['chat_log'][] = array('sender' => 'bot', 'message' => $bot_response);
    $messageBot = $message['message'];
    $_SESSION['Bot']= $bot_response;
    
    header("Location: index.php?send=Success");
         exit();
}

 function firstAnswer(){
       
    $messages = array(
        "Hello How i Can assist you today?",
         "How can I help you today?",
        "Is there something specific you need assistance with?",
        "Feel free to ask me any questions you have.",
        "I'm here to help!",
        "Let me know how I can be of assistance.",
        "Don't hesitate to ask if you need anything.",
        "I'm happy to help in any way I can.",
        "What can I do for you today?",
        "How can I make your day better?",
        "Is there anything I can do to assist you?",
        "Let's get started, what do you need help with?",
        "How can I make your experience better?",
        "Don't be shy, ask me anything!"
    );
    
        $rand_index = array_rand($messages); // Get a random index from the messages array
        
        $rand_msg = $messages[$rand_index]; // Get the message at the random index
        return $rand_msg;
    }
function DontAns(){
       
        $messages = array(
            "I'm sorry, I don't understand what you're asking. ",
            "Sorry, I didn't understand that.",
            "I'm not sure what you mean.",
            "Could you please rephrase that?",
            "I'm having trouble understanding your request.",
            "I'm sorry, I didn't quite catch that.",
            "I'm sorry, I'm not sure what you're asking.",
            "I'm sorry, I'm having difficulty understanding.",
            "I'm sorry, I don't have an answer for that.",
            "I'm sorry, I couldn't find what you were looking for.",
            "I'm sorry, I couldn't process that.",
            "I'm sorry, that's beyond my scope of knowledge.",
            "I didn't get it, could you try again?",
            "I'm sorry, could you please repeat that?",
            "I'm sorry, I didn't catch that. ",
            "Sorry, what was that again?",
            "My apologies, I don't understand.",
            "Sorry, I didn't quite get that.",
            "I'm sorry, that's not clear to me.",
            "I'm sorry, I didn't get your meaning.",
            "I'm sorry, I don't know what you're asking.",
            "I'm sorry, I don't have the answer to that.",
            "I'm sorry, I'm not sure I can help with that.",
            "I'm sorry, I don't know how to respond to that.",
            "I'm sorry, I don't have a response for that.",
            "I'm sorry, that's outside my area of expertise.",
            "I'm sorry, I don't have any information on that.",
            "I'm sorry, that's not within my capabilities.",
            "I'm sorry, I don't have any knowledge about that.",
            "I'm sorry, I'm not sure what you're looking for.",
            "I'm sorry, that's not something I can assist with.",
            "I'm sorry, I'm not able to answer that question.",
            "I'm sorry, I don't have a clear understanding of what you're asking.",
            "I'm sorry, that's not a request I can fulfill.",
            "I'm sorry, I don't have the expertise to assist with that.",
            "I'm sorry, that's beyond my area of expertise.",
            "I'm sorry, I don't have the information you're looking for.",
            "I'm sorry, I don't have an appropriate response for that.",
            "I'm sorry, I don't have a solution for that problem.",
            "I'm sorry, I don't have a suggestion for that.",
            "I'm sorry, I don't have any ideas for that.",
            "I'm sorry, I'm not able to provide an answer at this time.",
            "I'm sorry, I'm not sure how to help you with that.",
            "I'm sorry, I don't have any recommendations at this time.",
            "I'm sorry, I don't know what to suggest.",
            "I'm sorry, I don't have any feedback on that.",
            "I'm sorry, I don't have any input on that.",
            "I'm sorry, I don't have any comments on that.",
            "I'm sorry, I don't have a response for that question.",
            "I'm sorry, I don't have an answer to that at the moment.",
            "I'm sorry, I don't have any insights to offer on that topic.",
            "I'm sorry, I'm not sure what advice to give.",
        );
        
            $rand_index = array_rand($messages); // Get a random index from the messages array
            
            $rand_msg = $messages[$rand_index]; // Get the message at the random index
            return $rand_msg;
   }
 if(isset($_POST['Has-Sumitted'])){
    
    
    function Answer($Sotreddata) {
        
        $input = strtolower($_POST['user_input']);
      foreach ($Sotreddata as $keyword => $response) {
        if (strtolower($input) == strtolower($keyword)) {
            return $response;
        }
    }
                // if no keyword was found, provide a default response
                return DontAns();
            
    }
    
    $user_message = $_POST['user_input'];
    
    // Add user message to chat log
    $_SESSION['chat_log'][] = array('sender' => 'user', 'message' => $user_message);
    // Get bot response
    $bot_response = Answer($Sotreddata);
    // Add bot response to chat log
    $_SESSION['chat_log'][] = array('sender' => 'bot', 'message' => $bot_response);
    $messageBot = $message['message'];
    $_SESSION['Bot']= $bot_response;
    header("Location: index.php?send=Success");
         exit();

}
?>